# Generated by Django 4.2.3 on 2024-04-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('PROD_NO', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('BuyType', models.CharField(max_length=100)),
                ('DSCType', models.CharField(max_length=100)),
                ('heightsize', models.IntegerField(help_text='Height in millimeters')),
                ('widthsize', models.IntegerField(help_text='Width in millimeters')),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='stickers/')),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
