# Generated by Django 4.2.3 on 2024-04-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='BuyType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='DSCType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='heightsize',
            field=models.IntegerField(help_text='Height in millimeters', null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stickers/'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='widthsize',
            field=models.IntegerField(help_text='Width in millimeters', null=True),
        ),
    ]
