# Generated by Django 4.2.3 on 2024-04-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packing', '0002_alter_sticker_buytype_alter_sticker_dsctype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='stickers/'),
        ),
    ]
