# Generated by Django 4.2.3 on 2024-04-19 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Packing', '0003_alter_sticker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stickers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='BuyType',
            field=models.CharField(choices=[('自印', '自印'), ('外購', '外購')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='DSCType',
            field=models.CharField(choices=[('標準', '標準'), ('依訂單不同', '依訂單不同')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='color',
            field=models.CharField(choices=[('彩色', '彩色'), ('黑白', '黑白'), ('透明', '透明')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='material',
            field=models.CharField(choices=[('牛皮紙', '牛皮紙'), ('白紙', '白紙'), ('透明材質', '透明材質')], max_length=100, null=True),
        ),
    ]
