"""
Django settings for workFlow project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hgw*7la_5uez2qm!e%qr*2bb=c)o)eq^1^++3c%jdq%@yow+1@'

# SECURITY WARNING: don't run with debug turned on in production!
# 部屬時需要修改 # 開發時 True # 部屬時 False
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
CRISPY_TEMPLATE_PACK = 'bootstrap5'

INSTALLED_APPS = [
    'rest_framework',
    'django_crontab',
    'crispy_forms',
    "HumanResource",
    'AssembleWmodel',
    'Production_management',
    "SignatureBusiness",
    "R_D_Department",
    "Assembly",
    "GeneralManagersOffice",
    "Company",
    "QualityAssurance",
    "ITInformation",
    "KnowledgeDatabase",
    "Packing",
    'django_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    "schedule"
]

CRONJOBS = [
    ('0 8 * * *', 'Company.Email_Send.sendDailyEmail'),
    ('0 * * * *', 'Company.Write_model.Write_Employee'),  # 每小時執行一次
    ('30 8 * * *', 'Company.Write_model.check_user_if_alive'),
    ('30 9 * * *', 'Production_management.update_daily_value.update_daily_value'),
    ('30 10 * * *', 'Production_management.update_daily_value.update_daily_yearly_data'),
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'workFlow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'workFlow.wsgi.application'


# DEBUG
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',  # 更改为DEBUG
            'class': 'logging.FileHandler',
            'filename': 'django_errors.log',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'my_logger': {
            'handlers': ['file'],
            'level': 'DEBUG',  # 更改为DEBUG
            'propagate': True,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'YBICO',
        'USER': 'MIS',
        'PASSWORD': '22067856',
        'HOST': '192.168.2.10',
        'PORT': '1433',
    }
}

# 本地測試 # 這邊部屬時要把註解加上
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# 部屬時需要修改 # 這邊部屬時要把註解拿掉
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
#         'LOCATION': '127.0.0.1:11211',
#     }
# }

# table 裡面django的
# auth系列
# djaogo


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
# UserAttributeSimilarityValidator：檢查密碼是否和用戶的其他屬性過於相似。
# MinimumLengthValidator：檢查密碼的長度是否達到要求。
# CommonPasswordValidator：檢查密碼是否在常見密碼列表中。
# NumericPasswordValidator：檢查密碼是否只包含數字。
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# 客製化的驗證機制
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# STATIC_URL 定義了 Django 在 URL 中使用的靜態文件前綴，通常設為 '/static/'。
# 本地測試使用
STATIC_URL = '/static/'  

# 部屬時需要修改
# STATIC_URL = '/staticfiles/' 

# STATICFILES_DIRS 是一個包含你的所有靜態文件目錄的列表。例如：
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'Company.CustomUser'

# 給每一個對話一個存活期限(defult = 2 Week)
# SESSION_COOKIE_AGE =


# 用來控制用戶的登入頁面
LOGIN_URL = '/login'


# 用戶上傳文件 # 保存用戶上傳文件的目錄的絕對文件系統路徑。
MEDIA_ROOT = BASE_DIR / 'uploads'

# 讓用戶可以使用所上傳文件往址
MEDIA_URL = '/uploads/'


LANGUAGE_CODE = 'zh-Hant'
TIME_ZONE = 'Asia/Taipei'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# 以下為富文本區塊
# CKEDITOR_BASEPATH = "/staticfiles/ckeditor/ckeditor/"
# 感覺暫時不用設計
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_CONFIGS = {
    # 自己自訂意出來的
    'awesome_ckeditor': {
        'language': 'zh-Hant',  # 举例使用简体中文
        'skin': 'moono-lisa',
        'toolbar': [
            {'name': 'clipboard', 'items': ['Undo', 'Redo']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'editing', 'items': [
                'Find', 'Replace', '-', 'SelectAll']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'styles', 'items': [
                'Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            '/',
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'Html5video']},
        ],
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            # 'uploadimage',  # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'html5video'
        ]),
    },



    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': [
                'Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': [
                'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': [
                'Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                       'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': [
                'Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 291,
        # 'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',  # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}

# 啟動日歷的檢查權限
CALENDAR_VIEW_PERM = True