# Generated by Django 4.2.3 on 2023-07-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonnelAdditionApplication',
        ),
    ]
