# Generated by Django 4.2.3 on 2023-11-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalFactName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('factoryname', models.CharField(max_length=100, verbose_name='加工廠商')),
                ('makename', models.CharField(max_length=100, verbose_name='加工製程')),
            ],
            options={
                'unique_together': {('form_id', 'item')},
            },
        ),
    ]
