# Generated by Django 4.2.3 on 2023-11-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbnormalFactName',
            new_name='djangoabnormalfactname',
        ),
    ]
