# Generated by Django 4.2.3 on 2023-11-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0002_rename_abnormalfactname_djangoabnormalfactname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='djangoabnormalfactname',
            new_name='abnormalfactname',
        ),
    ]
