# Generated by Django 4.2.3 on 2023-11-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0003_rename_djangoabnormalfactname_abnormalfactname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abnormalfactname',
            new_name='AbnormalFactna',
        ),
    ]
