# Generated by Django 4.2.3 on 2023-11-15 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0004_rename_abnormalfactname_abnormalfactna'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbnormalFactna',
        ),
    ]
