# Generated by Django 4.2.3 on 2023-11-15 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbnormalFactna',
        ),
    ]
