# Generated by Django 4.2.3 on 2023-11-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_number', models.CharField(max_length=100, verbose_name='MK單號')),
                ('form_id', models.CharField(max_length=100, verbose_name='重工單號')),
                ('item', models.CharField(max_length=100, verbose_name='令次')),
                ('remarks', models.TextField(verbose_name='備註')),
                ('unit_price', models.FloatField(verbose_name='單價')),
                ('total_price', models.FloatField(verbose_name='總價')),
            ],
        ),
        migrations.AlterField(
            model_name='abnormalfactna',
            name='form_id',
            field=models.CharField(max_length=100, verbose_name='重工單號'),
        ),
        migrations.AlterField(
            model_name='abnormalfactna',
            name='item',
            field=models.CharField(max_length=100, verbose_name='令次'),
        ),
    ]
