# Generated by Django 4.2.3 on 2023-11-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0009_abnormalmk_alter_abnormalfactna_form_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abnormalmk',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='abnormalmk',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='abnormalfactna',
            name='total_price',
            field=models.FloatField(null=True, verbose_name='總價'),
        ),
        migrations.AddField(
            model_name='abnormalfactna',
            name='unit_price',
            field=models.FloatField(null=True, verbose_name='單價'),
        ),
    ]
