# Generated by Django 4.2.3 on 2024-05-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0011_remove_abnormalmk_id_alter_abnormalmk_mk_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormalmk',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abnormalmk',
            name='mk_number',
            field=models.CharField(max_length=100, verbose_name='MK單號'),
        ),
    ]
