# Generated by Django 4.2.3 on 2024-05-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0012_abnormalmk_id_alter_abnormalmk_mk_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbnormalMK',
        ),
    ]
