# Generated by Django 4.2.3 on 2024-05-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualityAssurance', '0013_delete_abnormalmk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_number', models.CharField(max_length=100, verbose_name='MK單號')),
                ('form_id', models.CharField(max_length=100, verbose_name='重工單號')),
                ('item', models.CharField(max_length=100, verbose_name='令次')),
                ('remarks', models.TextField(verbose_name='備註')),
            ],
        ),
    ]
