# Generated by Django 4.2.3 on 2024-02-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDatabase_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='專案名稱')),
                ('tags', models.TextField(verbose_name='標籤')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='建立日期')),
                ('applicant', models.CharField(max_length=100)),
            ],
        ),
    ]
