# Generated by Django 4.2.3 on 2024-02-22 03:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedatabase_model',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
