# Generated by Django 4.2.3 on 2024-02-22 07:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeDatabase', '0002_knowledgedatabase_model_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedatabase_model',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='knowledgedatabase_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立日期'),
        ),
    ]
