# Generated by Django 4.2.3 on 2024-02-27 02:34

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeDatabase', '0003_alter_knowledgedatabase_model_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedatabase_model',
            name='last_edit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='最後修改日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgedatabase_model',
            name='unit',
            field=models.CharField(max_length=100, null=True, verbose_name='部門'),
        ),
        migrations.AlterField(
            model_name='knowledgedatabase_model',
            name='applicant',
            field=models.CharField(max_length=100, verbose_name='申請人'),
        ),
        migrations.AlterField(
            model_name='knowledgedatabase_model',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='文章'),
        ),
    ]
