# Generated by Django 4.2.3 on 2024-05-08 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0046_richtext'),
        ('schedule', '0015_alter_event_end_alter_event_end_recurring_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.form', verbose_name='form'),
        ),
    ]
