# Generated by Django 4.2.3 on 2024-05-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_alter_event_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='form'),
        ),
    ]
