# Generated by Django 4.2.3 on 2024-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_alter_event_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('visitor_name', models.CharField(max_length=255, verbose_name='Visitor Name')),
                ('purpose', models.CharField(max_length=500, verbose_name='Purpose of Visit')),
                ('number_of_visitors', models.IntegerField(verbose_name='Number of Visitors')),
                ('interviewee_name', models.CharField(max_length=255, verbose_name='Interviewee Name ')),
                ('vehicle_license_plate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vehicle License Plate')),
                ('identification_document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identification Document Number')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitor',
            },
        ),
    ]
