# Generated by Django 4.2.3 on 2024-05-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
    ]
