# Generated by Django 4.2.3 on 2024-05-14 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0020_alter_visitor_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visitors', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
