# Generated by Django 4.2.3 on 2024-05-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_event_form_without_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='company_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company ID'),
        ),
    ]
