# Generated by Django 4.2.3 on 2024-05-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_visitor_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='form',
            new_name='form_id',
        ),
    ]
