# Generated by Django 4.2.3 on 2024-05-15 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0025_visitor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='interviewee_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
