# Generated by Django 4.2.3 on 2024-05-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_alter_visitor_interviewee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='interviewee_name',
            field=models.CharField(default='', max_length=255, verbose_name='Interviewee Name '),
            preserve_default=False,
        ),
    ]
