# Generated by Django 4.2.3 on 2024-08-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_alter_visitor_interviewee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='identification_document_number',
        ),
        migrations.AddField(
            model_name='visitor',
            name='tellphone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='contact number in the company'),
        ),
    ]
