# Generated by Django 4.2.3 on 2023-12-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('form_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
