# Generated by Django 4.2.3 on 2024-07-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('R_D_Department', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
