# Generated by Django 4.2.1 on 2023-06-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='location',
            new_name='FullName',
        ),
    ]
