# Generated by Django 4.2.1 on 2023-06-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_rename_location_customuser_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('form_name', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('application_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('version_number', models.CharField(max_length=100)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'forms',
            },
        ),
    ]
