# Generated by Django 4.2.1 on 2023-06-26 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_form'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='form',
            table='Company_forms',
        ),
    ]
