# Generated by Django 4.2.1 on 2023-06-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_alter_form_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='application_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='closing_date',
            field=models.CharField(max_length=100),
        ),
    ]
