# Generated by Django 4.2.1 on 2023-06-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_alter_form_application_date_alter_form_closing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('station_number', models.CharField(max_length=255)),
                ('station_name', models.CharField(max_length=255)),
                ('next_station', models.CharField(max_length=255)),
                ('previous_station', models.CharField(max_length=255)),
                ('station_choice', models.CharField(max_length=255)),
                ('station_manager', models.CharField(max_length=255)),
                ('station_group', models.CharField(max_length=255)),
                ('station_mode', models.CharField(max_length=255)),
                ('endorsement', models.CharField(max_length=255)),
                ('limited_time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Company_levels',
                'unique_together': {('level_id', 'station_number')},
            },
        ),
    ]
