# Generated by Django 4.2.1 on 2023-06-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='level',
            name='endorsement',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='level',
            name='station_number',
        ),
    ]
