# Generated by Django 4.2.1 on 2023-06-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_alter_level_unique_together_alter_level_endorsement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
