# Generated by Django 4.2.1 on 2023-06-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_level_level_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='endorsement',
            new_name='endorsement_manager',
        ),
    ]
