# Generated by Django 4.2.1 on 2023-06-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_level_endorsement_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('worker_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('supervisor_id', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('position_name', models.CharField(max_length=100)),
                ('department_level', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Company_employee',
            },
        ),
    ]
