# Generated by Django 4.2.1 on 2023-06-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0012_alter_level_limited_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='versionNumber',
            field=models.CharField(default='', max_length=255),
        ),
    ]
