# Generated by Django 4.2.1 on 2023-06-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_level_versionnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('applicant', models.CharField(max_length=100)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.form')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.level')),
            ],
            options={
                'db_table': 'Company_process',
            },
        ),
    ]
