# Generated by Django 4.2.1 on 2023-06-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0014_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='level_id',
            field=models.CharField(max_length=100),
        ),
    ]
