# Generated by Django 4.2.1 on 2023-06-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_alter_process_level_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='applicant',
        ),
    ]
