# Generated by Django 4.2.1 on 2023-07-03 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0018_remove_process_real_id_alter_process_real_process_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_record', models.CharField(max_length=100)),
                ('approval_opinion', models.CharField(max_length=500)),
                ('approval_time', models.CharField(max_length=100)),
                ('approval_status', models.CharField(max_length=100)),
                ('process_status', models.CharField(max_length=50)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.process')),
            ],
            options={
                'db_table': 'Company_history',
            },
        ),
    ]
