# Generated by Django 4.2.1 on 2023-07-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_process_history'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='process_history',
            table='Company_process_history',
        ),
    ]
