# Generated by Django 4.2.1 on 2023-07-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0021_alter_process_history_process_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_history',
            name='process_status',
        ),
    ]
