# Generated by Django 4.2.1 on 2023-07-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0022_remove_process_history_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='endorsement_mode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
