# Generated by Django 4.2.1 on 2023-07-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0023_level_endorsement_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='endorsement_allow',
            field=models.BooleanField(default=False),
        ),
    ]
