# Generated by Django 4.2.1 on 2023-07-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0024_level_endorsement_allow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='endorsement_allow',
        ),
    ]
