# Generated by Django 4.2.1 on 2023-07-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0025_remove_level_endorsement_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_real',
            name='endorsement_allow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process_real',
            name='endorsement_approvers',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
