# Generated by Django 4.2.1 on 2023-07-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0026_process_real_endorsement_allow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_real',
            name='endorsement_allow',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
