# Generated by Django 4.2.1 on 2023-07-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0028_process_real_endorsement_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='path/to/save')),
            ],
            options={
                'db_table': 'Company_attachment',
            },
        ),
        migrations.AddField(
            model_name='form',
            name='attachments',
            field=models.ManyToManyField(to='Company.attachment'),
        ),
    ]
