# Generated by Django 4.2.1 on 2023-07-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0029_attachment_form_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='PersonnelAdditionApplication'),
        ),
    ]
