# Generated by Django 4.2.3 on 2023-07-24 05:28

import Company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0030_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=Company.models.get_upload_to),
        ),
        migrations.AlterField(
            model_name='process_real',
            name='endorsement_count',
            field=models.IntegerField(default=0),
        ),
    ]
