# Generated by Django 4.2.3 on 2023-07-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0031_alter_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='station_manager',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
