# Generated by Django 4.2.3 on 2023-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0034_alter_level_limited_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='limited_time',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='level',
            name='station_manager',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
