# Generated by Django 4.2.3 on 2023-07-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0036_alter_level_endorsement_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='parents_form_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
