# Generated by Django 4.2.3 on 2023-07-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0037_form_parents_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='endorsement_group',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
