# Generated by Django 4.2.3 on 2023-08-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0038_alter_level_endorsement_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_history',
            name='approval_opinion',
            field=models.CharField(max_length=2000),
        ),
    ]
