# Generated by Django 4.2.3 on 2023-08-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0039_alter_process_history_approval_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_real',
            name='endorsement_asign',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
