# Generated by Django 4.2.3 on 2023-08-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0040_process_real_endorsement_asign'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='resourcenumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
