# Generated by Django 4.2.3 on 2024-07-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0047_remove_attachment_form_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='form_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attachment',
            name='form_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
