# Generated by Django 4.2.3 on 2024-07-04 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0048_attachment_form_id_attachment_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.form'),
        ),
        migrations.AlterField(
            model_name='process_real',
            name='process_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Company.process'),
        ),
    ]
